name: dab-azure-cosmos-db-nosql-quickstart
services:
  api:
    project: ./src/api
    language: python
    host: containerapp
    docker:
      path: Dockerfile
      context: ./
  web:
    project: ./src/web
    language: csharp
    host: containerapp
    docker:
      path: Dockerfile
      context: ./
pipeline:
  provider: github
metadata:
  template: dab-azure-cosmos-db-nosql-quickstart@0.0.1-beta
